
ALTER TABLE public.assistant_api_deployments DROP COLUMN ideal_timeout_backoff;
ALTER TABLE public.assistant_debugger_deployments DROP COLUMN ideal_timeout_backoff;
ALTER TABLE public.assistant_whatsapp_deployments DROP COLUMN ideal_timeout_backoff;
ALTER TABLE public.assistant_phone_deployments DROP COLUMN ideal_timeout_backoff;